Update installation.md
Received an error when trying to download and transfer the singularity image using the command located in the Singularity, Running Offline section. See below:

"[user]$ singularity pull --name nf-core-rnaseq-1.3.img docker://nf-core/rnaseq:1.3
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/nf-core/rnaseq:1.3
ERROR UNAUTHORIZED: authentication required
ERROR Check existence, naming, and permissions
Cleaning up...
ERROR: pulling container failed!"

I found a related issue posted in a different nf-core pipeline (see here https://github.com/nf-core/chipseq/issues/8). And was able to fix the issue by removing the "-" in nf-core.